version: "3"

services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  database_pg_admin:
    image: dpage/pgadmin4
    ports:
        - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
  web:
    build: ./web/
    ports:
      - "8000:8000"
    volumes:
      - ./web:/code
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    #command: django-admin startproject django_app .
